/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author JorgeLuis
 */
public class Bienvenido extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenido
     */
    public Bienvenido() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaPrimerNumero = new javax.swing.JLabel();
        campoNumero1 = new javax.swing.JTextField();
        etiquetaSegundoNumero = new javax.swing.JLabel();
        campoNumero2 = new javax.swing.JTextField();
        botonSumar = new javax.swing.JButton();
        etiquetaResultado = new javax.swing.JLabel();
        campoResultado = new javax.swing.JTextField();
        BotonRestar = new javax.swing.JButton();
        BotonMultiplicar = new javax.swing.JButton();
        BotonDividir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenidos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaPrimerNumero.setText("Primer número:");
        getContentPane().add(etiquetaPrimerNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 14, -1, -1));

        campoNumero1.setText("12");
        campoNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumero1ActionPerformed(evt);
            }
        });
        getContentPane().add(campoNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 11, 131, -1));

        etiquetaSegundoNumero.setText("Segundo número:");
        getContentPane().add(etiquetaSegundoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        campoNumero2.setText("12");
        campoNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumero2ActionPerformed(evt);
            }
        });
        getContentPane().add(campoNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 37, 131, -1));

        botonSumar.setText("Sumar");
        botonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumarActionPerformed(evt);
            }
        });
        getContentPane().add(botonSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, -1));

        etiquetaResultado.setText("Resultado:");
        getContentPane().add(etiquetaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 100, -1, -1));

        campoResultado.setEditable(false);
        campoResultado.setFocusable(false);
        getContentPane().add(campoResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 97, 131, -1));

        BotonRestar.setText("Restar");
        BotonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 68, -1, -1));

        BotonMultiplicar.setText("Multiplicar");
        BotonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 68, -1, -1));

        BotonDividir.setText("Dividir");
        BotonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDividirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 68, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumarActionPerformed
        String texto1 = campoNumero1.getText();
        try {
            int num1 = Integer.parseInt(texto1);
            int num2 = Integer.parseInt(campoNumero2.getText());
            int resultado = num1 + num2;
            String textoResultado = Integer.toString(resultado);
            campoResultado.setText(textoResultado);
        } catch(NumberFormatException nfe ) {
            JOptionPane.showMessageDialog(this, "Sólo se admiten números");
        }
    }//GEN-LAST:event_botonSumarActionPerformed

    private void BotonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestarActionPerformed
       String texto1 = campoNumero1.getText();
        try {
            int num1 = Integer.parseInt(texto1);
            int num2 = Integer.parseInt(campoNumero2.getText());
            int resultado = num1 - num2;
            String textoResultado = Integer.toString(resultado);
            campoResultado.setText(textoResultado);
        } catch(NumberFormatException nfe ) {
            JOptionPane.showMessageDialog(this, "Sólo se admiten números");
        }
    }//GEN-LAST:event_BotonRestarActionPerformed

    private void BotonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultiplicarActionPerformed
        String texto1 = campoNumero1.getText();
        try {
            int num1 = Integer.parseInt(texto1);
            int num2 = Integer.parseInt(campoNumero2.getText());
            int resultado = num1 * num2;
            String textoResultado = Integer.toString(resultado);
            campoResultado.setText(textoResultado);
        } catch(NumberFormatException nfe ) {
            JOptionPane.showMessageDialog(this, "Sólo se admiten números");
        }
    }//GEN-LAST:event_BotonMultiplicarActionPerformed

    private void BotonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDividirActionPerformed
        String texto1 = campoNumero1.getText();
        try {
            int num1 = Integer.parseInt(texto1);
            int num2 = Integer.parseInt(campoNumero2.getText());
            int resultado = num1 / num2;
            String textoResultado = Integer.toString(resultado);
            campoResultado.setText(textoResultado);
        } catch(NumberFormatException nfe ) {
            JOptionPane.showMessageDialog(this, "Sólo se admiten números");
        }
    }//GEN-LAST:event_BotonDividirActionPerformed

    private void campoNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumero1ActionPerformed

    private void campoNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumero2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDividir;
    private javax.swing.JButton BotonMultiplicar;
    private javax.swing.JButton BotonRestar;
    private javax.swing.JButton botonSumar;
    private javax.swing.JTextField campoNumero1;
    private javax.swing.JTextField campoNumero2;
    private javax.swing.JTextField campoResultado;
    private javax.swing.JLabel etiquetaPrimerNumero;
    private javax.swing.JLabel etiquetaResultado;
    private javax.swing.JLabel etiquetaSegundoNumero;
    // End of variables declaration//GEN-END:variables
}
